version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9100:9000"
    environment:
      ZK_HOSTS: "192.168.1.30:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
